export { default as Header } from './header';
export { default as HomePage } from './home-page';
export { default as LoginPage } from './login-page';
export { default as QuizPage } from './quiz-page';
export { default as AnalizingPage } from './analizing-page';
export { default as AnalysisReadyPage } from './analysis-ready-page';
export { default as AfterRegisterPaymentPage } from './after-register-payment-page';
export { default as Footer } from './footer';
export { default as Stepper } from './stepper';
